export PROJECT = auth-microservice
IMPORT_PATH := github.com/OscarTango1995/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
    --link auth-microservice-mongo-db:auth-microservice-mongo-db \
    --link auth-microservice-mysql-db:auth-microservice-mysql-db \
    ${DEV_IMAGE}
